import React, { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Wallet, Search, Filter, Download, ArrowUpRight, CheckCircle2, Clock } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { 
  Table, 
  TableBody, 
  TableCell, 
  TableHead, 
  TableHeader, 
  TableRow 
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { KPICard } from "@/components/KPICard";
import referralApi from "@/lib/api/referral";

export default function GlobalReferralEarnings() {
  const [searchTerm, setSearchTerm] = useState("");

  const { data: earnings = [], isLoading } = useQuery({
    queryKey: ["admin-referral-earnings"],
    queryFn: referralApi.adminGetEarnings,
  });

  const { data: stats } = useQuery({
    queryKey: ["admin-referral-stats"],
    queryFn: referralApi.adminGetStats,
  });

  const filteredEarnings = earnings.filter(row => 
    row.referrer_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    row.referred_user_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    row.order_id.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Referral Earnings Log</h1>
          <p className="text-muted-foreground">
            View all referral-based commissions and payouts generated by the profit engine.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm">
            <Download className="mr-2 h-4 w-4" />
            Export CSV
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <KPICard 
          title="Total Payouts" 
          value={`₹${Number(stats?.total_commissions_paid || 0).toLocaleString()}`} 
          icon={Wallet} 
          variant="profit"
          change="+15.2%"
          changeType="positive"
        />
        <KPICard 
          title="Pending Commissions" 
          value="₹45,200" 
          icon={Clock} 
          variant="warning"
        />
        <KPICard 
          title="Avg. Commission" 
          value="₹240" 
          icon={ArrowUpRight} 
          variant="default"
        />
      </div>

      <Card>
        <CardHeader>
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <CardTitle>Global Earnings History</CardTitle>
              <CardDescription>
                Real-time log of referral rewards credited to user wallets.
              </CardDescription>
            </div>
            <div className="relative w-full md:w-72">
              <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
              <Input
                type="search"
                placeholder="Search by name, ID or order..."
                className="pl-8"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <div className="rounded-md border overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Date</TableHead>
                  <TableHead>Recipient (Referrer)</TableHead>
                  <TableHead>Source User</TableHead>
                  <TableHead>Order ID</TableHead>
                  <TableHead>Commission</TableHead>
                  <TableHead>Status</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {isLoading ? (
                  <TableRow>
                    <TableCell colSpan={6} className="h-24 text-center">
                      Loading earnings log...
                    </TableCell>
                  </TableRow>
                ) : filteredEarnings.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={6} className="h-24 text-center text-muted-foreground">
                      No earning records found.
                    </TableCell>
                  </TableRow>
                ) : (
                  filteredEarnings.map((row) => (
                    <TableRow key={row.id}>
                      <TableCell className="text-xs">
                        {new Date(row.created_at).toLocaleString()}
                      </TableCell>
                      <TableCell>
                        <span className="font-medium">{row.referrer_name}</span>
                      </TableCell>
                      <TableCell>
                        <span className="text-sm font-medium">{row.referred_user_name}</span>
                      </TableCell>
                      <TableCell className="font-mono text-xs font-semibold text-blue-600 dark:text-blue-400">
                        {row.order_id}
                      </TableCell>
                      <TableCell className="font-mono font-bold text-emerald-600 dark:text-emerald-400">
                        +₹{Number(row.gross_amount).toLocaleString()}
                      </TableCell>
                      <TableCell>
                        <Badge variant="outline" className={row.status === 'processed' ? 'bg-profit/10 text-profit border-profit/20' : ''}>
                          {row.status}
                        </Badge>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
